FROM ubuntu:20.04
ARG DEBIAN_FRONTEND=noninteractive

COPY common.sh lib.sh /
RUN /common.sh

COPY cmake.sh /
RUN /cmake.sh

COPY xargo.sh /
RUN /xargo.sh

COPY qemu.sh /
RUN /qemu.sh arm

COPY musl.sh /
RUN /musl.sh \
    TARGET=arm-linux-musleabihf \
    "COMMON_CONFIG += --with-arch=armv7-a \
                      --with-float=hard \
                      --with-mode=thumb \
                      --with-fpu=vfp"

ENV CROSS_SYSROOT=/usr/arm-linux-musleabihf
COPY musl-symlink.sh /
RUN /musl-symlink.sh $CROSS_SYSROOT armhf

COPY qemu-runner /

# Export all target binutils just in case required.
ENV CARGO_TARGET_THUMBV7NEON_UNKNOWN_LINUX_MUSLEABIHF_LINKER=arm-linux-musleabihf-gcc \
    CARGO_TARGET_THUMBV7NEON_UNKNOWN_LINUX_MUSLEABIHF_RUNNER="/qemu-runner armv7" \
    AR_thumbv7neon_unknown_linux_musleabihf=arm-linux-musleabihf-ar \
    AS_thumbv7neon_unknown_linux_musleabihf=arm-linux-musleabihf-as \
    CC_thumbv7neon_unknown_linux_musleabihf=arm-linux-musleabihf-gcc \
    CXX_thumbv7neon_unknown_linux_musleabihf=arm-linux-musleabihf-g++ \
    LD_thumbv7neon_unknown_linux_musleabihf=arm-linux-musleabihf-ld \
    NM_thumbv7neon_unknown_linux_musleabihf=arm-linux-musleabihf-nm \
    OBJCOPY_thumbv7neon_unknown_linux_musleabihf=arm-linux-musleabihf-objcopy \
    OBJDUMP_thumbv7neon_unknown_linux_musleabihf=arm-linux-musleabihf-objdump \
    RANLIB_thumbv7neon_unknown_linux_musleabihf=arm-linux-musleabihf-ranlib \
    READELF_thumbv7neon_unknown_linux_musleabihf=arm-linux-musleabihf-readelf \
    SIZE_thumbv7neon_unknown_linux_musleabihf=arm-linux-musleabihf-size \
    STRINGS_thumbv7neon_unknown_linux_musleabihf=arm-linux-musleabihf-strings \
    STRIP_thumbv7neon_unknown_linux_musleabihf=arm-linux-musleabihf-strip \
    BINDGEN_EXTRA_CLANG_ARGS_thumbv7neon_unknown_linux_musleabihf="--sysroot=$CROSS_SYSROOT" \
    QEMU_LD_PREFIX=$CROSS_SYSROOT \
    RUST_TEST_THREADS=1
