FROM ubuntu:18.04
ARG DEBIAN_FRONTEND=noninteractive

COPY common.sh lib.sh /
RUN /common.sh

COPY cmake.sh /
RUN /cmake.sh

COPY xargo.sh /
RUN /xargo.sh

ARG VERBOSE
COPY crosstool-ng.sh /
COPY cross-toolchains/docker/crosstool-config/aarch64_be-unknown-linux-gnu-cross.config /
RUN /crosstool-ng.sh aarch64_be-unknown-linux-gnu-cross.config 5

ENV PATH /x-tools/aarch64_be-unknown-linux-gnu/bin/:$PATH

COPY qemu.sh /
RUN /qemu.sh aarch64_be

ENV CROSS_SYSROOT=/x-tools/aarch64_be-unknown-linux-gnu/aarch64_be-unknown-linux-gnu/sysroot/
ENV CARGO_TARGET_AARCH64_BE_UNKNOWN_LINUX_GNU_LINKER=aarch64_be-unknown-linux-gnu-gcc \
    CARGO_TARGET_AARCH64_BE_UNKNOWN_LINUX_GNU_RUNNER=qemu-aarch64_be \
    CC_aarch64_be_unknown_linux_gnu=aarch64_be-unknown-linux-gnu-gcc \
    CXX_aarch64_be_unknown_linux_gnu=aarch64_be-unknown-linux-gnu-g++ \
    BINDGEN_EXTRA_CLANG_ARGS_aarch64_be_unknown_linux_gnu="--sysroot=$CROSS_SYSROOT" \
    QEMU_LD_PREFIX=$CROSS_SYSROOT \
    RUST_TEST_THREADS=1
