FROM ubuntu:20.04
ARG DEBIAN_FRONTEND=noninteractive

COPY common.sh lib.sh /
RUN /common.sh

COPY cmake.sh /
RUN /cmake.sh

COPY xargo.sh /
RUN /xargo.sh

ARG VERBOSE
COPY crosstool-ng.sh /
COPY cross-toolchains/docker/crosstool-config/mips-unknown-linux-uclibc-cross.config /
RUN /crosstool-ng.sh mips-unknown-linux-uclibc-cross.config 5

ENV PATH /x-tools/mips-unknown-linux-uclibc/bin/:$PATH

COPY deny-debian-packages.sh /
RUN TARGET_ARCH=mips /deny-debian-packages.sh

COPY qemu.sh /
RUN /qemu.sh mips

COPY qemu-runner base-runner.sh /

ENV CROSS_SYSROOT=/x-tools/mips-unknown-linux-uclibc/mips-unknown-linux-uclibc/sysroot/
ENV CARGO_TARGET_MIPS_UNKNOWN_LINUX_UCLIBC_LINKER=mips-unknown-linux-uclibc-gcc \
    CARGO_TARGET_MIPS_UNKNOWN_LINUX_UCLIBC_RUNNER="/qemu-runner mips" \
    CC_mips_unknown_linux_uclibc=mips-unknown-linux-uclibc-gcc \
    CXX_mips_unknown_linux_uclibc=mips-unknown-linux-uclibc-g++ \
    BINDGEN_EXTRA_CLANG_ARGS_mips_unknown_linux_uclibc="--sysroot=$CROSS_SYSROOT" \
    QEMU_LD_PREFIX="$CROSS_SYSROOT" \
    RUST_TEST_THREADS=1 \
    PKG_CONFIG_PATH="/usr/lib/mips-unknown-linux-uclibc/pkgconfig/:${PKG_CONFIG_PATH}"
