FROM ubuntu:18.04
ARG DEBIAN_FRONTEND=noninteractive

COPY common.sh lib.sh /
RUN /common.sh

COPY cmake.sh /
RUN /cmake.sh

COPY xargo.sh /
RUN /xargo.sh

COPY crosstool-ng.sh /
COPY cross-toolchains/docker/crosstool-config/s390x-unknown-linux-gnu-cross.config /
RUN /crosstool-ng.sh s390x-unknown-linux-gnu-cross.config 5

ENV PATH /x-tools/s390x-ibm-linux-gnu/bin/:$PATH

COPY qemu.sh /
RUN /qemu.sh s390x

COPY dropbear.sh /
RUN /dropbear.sh

COPY linux-image.sh /
RUN /linux-image.sh s390x

COPY linux-runner /

ENV CARGO_TARGET_S390X_UNKNOWN_LINUX_GNU_LINKER=s390x-ibm-linux-gnu-gcc \
    CARGO_TARGET_S390X_UNKNOWN_LINUX_GNU_RUNNER="/linux-runner s390x" \
    CC_s390x_unknown_linux_gnu=s390x-ibm-linux-gnu-gcc \
    CXX_s390x_unknown_linux_gnu=s390x-ibm-linux-gnu-g++ \
    BINDGEN_EXTRA_CLANG_ARGS_arm_unknown_linux_gnueabihf="--sysroot=/x-tools/s390x-ibm-linux-gnu/s390x-ibm-linux-gnu/sysroot/" \
    QEMU_LD_PREFIX=/x-tools/s390x-ibm-linux-gnu/s390x-ibm-linux-gnu/sysroot/ \
    RUST_TEST_THREADS=1
