FROM ubuntu:20.04
ARG DEBIAN_FRONTEND=noninteractive

COPY common.sh lib.sh /
RUN /common.sh

COPY cmake.sh /
RUN /cmake.sh

COPY xargo.sh /
RUN /xargo.sh

ARG VERBOSE
COPY crosstool-ng.sh /
COPY cross-toolchains/docker/crosstool-config/mipsel-unknown-linux-uclibc.config /
RUN /crosstool-ng.sh mipsel-unknown-linux-uclibc.config 5

ENV PATH /x-tools/mipsel-unknown-linux-uclibc/bin/:$PATH

COPY deny-debian-packages.sh /
RUN TARGET_ARCH=mipsel /deny-debian-packages.sh \
    binutils \
    binutils-mipsel-linux-gnu

COPY qemu.sh /
RUN /qemu.sh mipsel

COPY qemu-runner base-runner.sh /

ENV CARGO_TARGET_MIPSEL_UNKNOWN_LINUX_UCLIBC_LINKER=mipsel-unknown-linux-uclibc-gcc \
    CARGO_TARGET_MIPSEL_UNKNOWN_LINUX_UCLIBC_RUNNER="/qemu-runner mipsel" \
    CC_mipsel_unknown_linux_uclibc=mipsel-unknown-linux-uclibc-gcc \
    CXX_mipsel_unknown_linux_uclibc=mipsel-unknown-linux-uclibc-g++ \
    BINDGEN_EXTRA_CLANG_ARGS_mipsel_unknown_linux_uclibc="--sysroot=/usr/mipsel-unknown-linux-uclibc" \
    QEMU_LD_PREFIX=/usr/mipsel-unknown-linux-uclibc \
    RUST_TEST_THREADS=1 \
    PKG_CONFIG_PATH="/usr/lib/mipsel-unknown-linux-uclibc/pkgconfig/:${PKG_CONFIG_PATH}"
