FROM ubuntu:20.04
ARG DEBIAN_FRONTEND=noninteractive

COPY common.sh lib.sh /
RUN /common.sh

COPY cmake.sh /
RUN /cmake.sh

COPY xargo.sh /
RUN /xargo.sh

# `MACOS_SDK_URL` or `MACOS_SDK_FILE` must be provided. `MACOS_SDK_FILE`
# is the filename, while `MACOS_SDK_DIR` is the path relative to the current
# build context. We will copy the filename from the root directory to
# osxcross.
ARG MACOS_SDK_DIR="."
ARG MACOS_SDK_FILE="nonexistent"
ARG MACOS_SDK_URL
# wildcard workaround so we can copy the file only if it exists
COPY $MACOS_SDK_DIR/$MACOS_SDK_FILE* /
COPY cross-toolchains/docker/darwin.sh /
RUN /darwin.sh

COPY cross-toolchains/docker/darwin-symlink.sh /
RUN /darwin-symlink.sh

ENV CROSS_SYSROOT=/opt/osxcross/SDK/latest/usr
ENV PATH=$PATH:/opt/osxcross/bin \
    CROSS_TARGET=x86_64-apple-darwin

COPY cross-toolchains/docker/darwin-entry.sh /
ENTRYPOINT ["/darwin-entry.sh"]
