FROM ubuntu:20.04
ARG DEBIAN_FRONTEND=noninteractive

COPY common.sh lib.sh /
RUN /common.sh

COPY cmake.sh /
RUN /cmake.sh

COPY xargo.sh /
RUN /xargo.sh

COPY cross-toolchains/docker/llvm-mingw.sh /
RUN /llvm-mingw.sh

ENV PATH /usr/llvm-mingw/bin:$PATH

ENV CARGO_TARGET_AARCH64_PC_WINDOWS_GNU_LINKER=aarch64-w64-mingw32-gcc \
    CARGO_TARGET_AARCH64_PC_WINDOWS_GNU_RUNNER=wine \
    CC_aarch64_pc_windows_gnu=aarch64-w64-mingw32-gcc \
    CXX_aarch64_pc_windows_gnu=aarch64-w64-mingw32-g++ \
    BINDGEN_EXTRA_CLANG_ARGS_aarch64_pc_windows_gnu="--sysroot=/usr/llvm-mingw/aarch64-w64-mingw32"
